table mart_kpi_merchant_overall
	lineageTag: fea8c2ef-2c0b-4aba-9110-dabdd1a7e960

	measure 'Fraud Rate by Merchant' =
			
			DIVIDE(
				SUM('mart_kpi_merchant_overall'[amount_usd_fraud_total]),
				SUM('mart_kpi_merchant_overall'[amount_usd_total])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: af63ab55-a2bd-474a-aa9f-905d99b02a20

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	column merchant_name
		dataType: string
		lineageTag: ba6aae11-b2b3-4847-87fb-3920361b4d6b
		summarizeBy: none
		sourceColumn: merchant_name

		annotation SummarizationSetBy = Automatic

	column txn_count
		dataType: int64
		formatString: 0
		lineageTag: 3fcf9e75-0bdd-41ae-9808-d9c0ef541127
		summarizeBy: sum
		sourceColumn: txn_count

		annotation SummarizationSetBy = Automatic

	column fraud_txn_count
		dataType: int64
		formatString: 0
		lineageTag: 7d467268-c56b-4f99-8fdb-af2868ab0187
		summarizeBy: sum
		sourceColumn: fraud_txn_count

		annotation SummarizationSetBy = Automatic

	column fraud_rate
		dataType: double
		lineageTag: 7a2145f3-6fb6-48ce-bc71-214144a4aa0b
		summarizeBy: sum
		sourceColumn: fraud_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column amount_usd_total
		dataType: double
		lineageTag: 0de94027-9512-47c4-af16-839677c4abbe
		summarizeBy: sum
		sourceColumn: amount_usd_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column amount_usd_avg
		dataType: double
		lineageTag: db7cb56d-0fdb-4dc1-917d-5e8606c24e0b
		summarizeBy: sum
		sourceColumn: amount_usd_avg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column amount_usd_fraud_total
		dataType: double
		lineageTag: a95e69ba-6e07-4c66-9a87-9560464c821b
		summarizeBy: sum
		sourceColumn: amount_usd_fraud_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column distinct_users
		dataType: int64
		formatString: 0
		lineageTag: 4b2e04a3-ff96-4d08-b922-a6810a36a7b1
		summarizeBy: sum
		sourceColumn: distinct_users

		annotation SummarizationSetBy = Automatic

	column first_date_key
		dataType: int64
		formatString: 0
		lineageTag: 84b3a0fa-0478-4bfe-bf44-d7c9f94a0919
		summarizeBy: none
		sourceColumn: first_date_key

		annotation SummarizationSetBy = Automatic

	column last_date_key
		dataType: int64
		formatString: 0
		lineageTag: 135f2709-342f-43a3-80e4-039e88a593a0
		summarizeBy: sum
		sourceColumn: last_date_key

		annotation SummarizationSetBy = Automatic

	partition mart_kpi_merchant_overall = m
		mode: directQuery
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"crypto-minutia-490711-g8" = Source{[Name="crypto-minutia-490711-g8"]}[Data],
				    analytics_Schema = #"crypto-minutia-490711-g8"{[Name="analytics",Kind="Schema"]}[Data],
				    mart_kpi_merchant_overall_Table = analytics_Schema{[Name="mart_kpi_merchant_overall",Kind="Table"]}[Data]
				in
				    mart_kpi_merchant_overall_Table

	annotation PBI_ResultType = Table

